language: php
php:
  - '7.0'

before_script:
  - cp .env.travis .env
#  - mysql -e 'create database homestead;'
  - curl -s http://getcomposer.org/installer | php
  - composer self-update
  - php composer.phar install --dev
  - php artisan migrate
  - php artisan db:seed

script: phpunit
#script: php vendor/codeception/codeception/codecept run
